//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RayTracing.ModelFiles.Tests.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RayTracing.ModelFiles.Tests.TestData.TestFiles", typeof(TestFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;COLLADA xmlns=&quot;http://www.collada.org/2005/11/COLLADASchema&quot; version=&quot;1.4.1&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;asset&gt;
        ///    &lt;contributor&gt;
        ///      &lt;author&gt;Blender User&lt;/author&gt;
        ///      &lt;authoring_tool&gt;Blender 4.0.1 commit date:2023-11-16, commit time:16:40, hash:d0dd92834a08&lt;/authoring_tool&gt;
        ///    &lt;/contributor&gt;
        ///    &lt;created&gt;2023-12-05T16:02:34&lt;/created&gt;
        ///    &lt;modified&gt;2023-12-05T16:02:34&lt;/modified&gt;
        ///    &lt;unit name=&quot;meter&quot; meter=&quot;1&quot;/&gt;
        ///    &lt;up_axis&gt;Z_UP&lt;/u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DummyDae {
            get {
                return ResourceManager.GetString("DummyDae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;COLLADA xmlns=&quot;http://www.collada.org/2005/11/COLLADASchema&quot; version=&quot;1.4.1&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;asset&gt;
        ///    &lt;contributor&gt;
        ///      &lt;author&gt;Blender User&lt;/author&gt;
        ///      &lt;authoring_tool&gt;Blender 4.0.2 commit date:2023-12-05, commit time:07:41, hash:9be62e85b727&lt;/authoring_tool&gt;
        ///    &lt;/contributor&gt;
        ///    &lt;created&gt;2023-12-06T22:23:36&lt;/created&gt;
        ///    &lt;modified&gt;2023-12-06T22:23:36&lt;/modified&gt;
        ///    &lt;unit name=&quot;meter&quot; meter=&quot;1&quot;/&gt;
        ///    &lt;up_axis&gt;Z_UP&lt;/u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GlassDae {
            get {
                return ResourceManager.GetString("GlassDae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.77 (sub 0) OBJ File: &apos;indoor plant_02.blend&apos;
        ///# www.blender.org
        ///mtllib indoor plant_02.mtl
        ///o indoor_plant_02
        ///v 0.421644 5.303134 -1.634998
        ///v 0.425062 5.301006 -1.583781
        ///v 0.402986 5.316806 -1.679318
        ///v 0.436480 5.292621 -1.643623
        ///v 0.452523 5.283854 -1.569836
        ///v 0.396485 5.321778 -1.625102
        ///v 0.414313 5.307897 -1.716969
        ///v 0.597870 4.592344 -0.163347
        ///v 0.609894 4.433214 -0.067843
        ///v 0.546717 4.623752 -0.092687
        ///v 0.581346 4.735162 -0.272481
        ///v 0.653518 4.567615 -0.226185
        ///v 0.657935 4.40 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IndoorPlantObj {
            get {
                return ResourceManager.GetString("IndoorPlantObj", resourceCulture);
            }
        }
    }
}
